### ISSUE TITLE
Whoops — something went wrong! An error has been logged.

### ISSUE THREAD

**Issue by gabriel3002** [felipesanma/SImpleTTS#2]
Hola, lo primero agradecerte las molestias en crear este recurso.

He hecho todos los pasos que pones en el tutorial, pero me ha salido el error "Whoops — something went wrong! An error has been logged."

He accedido a la cloud de IBM, generado el recurso TTS, y utilizado tu TTS Tester con la APIKey y la URL del recurso, y luego he escrito para que me saque el audio del texto "hola mundo", y ha salido el error. 

Este error ha salido al usar tanto Chrome como firefox, y estoy utilizando un mac.

Gracias.

**Comment by felipesanma** [comment]
Hola Gabriel!

No hay problema, de hecho, gracias por usarlo :)

Acabo de hacer una prueba y funcionó perfect, mira:

![image](https://user-images.githubusercontent.com/50891841/126655403-b1f37090-18bf-40ca-89f8-6e0c78fa9a1b.png)

¿Puedes grabar un video loom con el proceso de lo que haces? (para identificar por qué te da error)

@gabriel3002

**Comment by gabriel3002** [comment]
He hecho un video del incidente y lo he subido a drive. Te paso el enlace.

https://drive.google.com/file/d/1BRh_Ym5KapGjxEXO5PGlCPYFEJluFtH3/view?usp=sharing

**Comment by felipesanma** [comment]
@gabriel3002 subí una nueva versión para mostrar el error

![image](https://user-images.githubusercontent.com/50891841/126807700-5ef9771d-8dab-4d32-bffb-b8c7a2de3eb9.png)


¿Puedes probar nuevamente por favor?

**Comment by felipesanma** [comment]
@gabriel3002 puedo cerrar el caso ?

**Comment by gabriel3002** [comment]
Funciona perfecto ahora, gracias

**Comment by felipesanma** [comment]
Perfecto 🍡
